services:
  db:
    image: postgres:16-alpine
    container_name: nextcloud-db
    restart: always
    environment:
      POSTGRES_DB: nextcloud
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: nextcloud
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C.UTF-8"
    volumes:
      - ./data/db:/var/lib/postgresql/data:z

  redis:
    image: redis:alpine
    container_name: nextcloud-redis
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./data/redis:/data:z

  app:
    image: nextcloud:fpm-alpine
    container_name: nextcloud-app
    restart: always
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: nextcloud
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: nextcloud
      REDIS_HOST: redis
      NEXTCLOUD_TRUSTED_DOMAINS: nextcloud.local
      NEXTCLOUD_TRUSTED_PROXIES: proxy
      OVERWRITEPROTOCOL: https
      OVERWRITEHOST: nextcloud.local
      OVERWRITECLIURL: https://nextcloud.local
    extra_hosts: ["nextcloud.local:127.0.0.1"]
    volumes:
      - ./data/nextcloud:/var/www/html:z
    depends_on:
      - db
      - redis

  collabora:
    image: collabora/code:latest
    container_name: nextcloud-collabora
    restart: always
    environment:
      domain: nextcloud\.local
      extra_params: --o:ssl.enable=false --o:ssl.termination=true
    cap_add: [MKNOD]
    volumes:
      - ./data/collabora:/opt/lool/child-roots:z

  proxy:
    image: nginx:alpine
    container_name: nextcloud-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro,z
      - ./nginx/conf.d:/etc/nginx/conf.d:ro,z
      - ./nginx/certs:/etc/nginx/certs:ro,z
      - ./data/nextcloud:/var/www/html:ro,z
    depends_on:
      - app
      - collabora

networks:
  default:
    name: nextcloud_net
    driver: bridge

